In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
a = pd.read_csv('IPL_AUCTION_2013-2022.csv')
batting = pd.read_csv('batting_consolidated.csv')
bowling = pd.read_csv('bowl_consolidated.csv')

In [3]:
bat = a[a['TYPE']=='Batsman'].reset_index()
bat.drop('index',axis=1,inplace=True)

bat

TID                     PID             PLAYER  \
0            2022-Mumbai Indians       Ishan Kishan-2022       Ishan Kishan   
1     2022-Kolkata Knight Riders       Shreyas Iyer-2022       Shreyas Iyer   
2       2022-Sunrisers Hyderabad    Nicholas Pooran-2022    Nicholas Pooran   
3          2022-Rajasthan Royals    Shimron Hetmyer-2022    Shimron Hetmyer   
4       2022-Sunrisers Hyderabad     Rahul Tripathi-2022     Rahul Tripathi   
...                          ...                     ...                ...   
1124                   2013-NONE  Dilshan Munaweera-2013  Dilshan Munaweera   
1125                   2013-NONE  Lahiru Thirimanne-2013  Lahiru Thirimanne   
1126                   2013-NONE       Henry Davids-2013       Henry Davids   
1127                   2013-NONE      Rilee Rossouw-2013      Rilee Rossouw   
1128                   2013-NONE      Kaushal Silva-2013      Kaushal Silva   

     NATIONALITY     TYPE   PRICE SOLD/UNSOLD                   TEAM  YEAR  
0         Indian  Batsman  152.50        SOLD         Mumbai Indians  2022  
1         Indian  Batsman  122.50        SOLD  Kolkata Knight Riders  2022  
2       Overseas  Batsman  107.50        SOLD    Sunrisers Hyderabad  2022  
3       Overseas  Batsman   85.00        SOLD       Rajasthan Royals  2022  
4         Indian  Batsman   85.00        SOLD    Sunrisers Hyderabad  2022  
...          ...      ...     ...         ...                    ...   ...  
1124    Overseas  Batsman    1.17      UNSOLD                   NONE  2013  
1125    Overseas  Batsman    1.17      UNSOLD                   NONE  2013  
1126    Overseas  Batsman    1.17      UNSOLD                   NONE  2013  
1127    Overseas  Batsman    1.17      UNSOLD                   NONE  2013  
1128    Overseas  Batsman    1.17      UNSOLD                   NONE  2013  

[1129 rows x 9 columns]

In [4]:
bowl = a[a['TYPE']=='Bowler'].reset_index()
bowl.drop('index',axis=1,inplace=True)

bowl

TID                    PID            PLAYER  \
0      2022-Chennai Super Kings     Deepak Chahar-2022     Deepak Chahar   
1           2022-Delhi Capitals    Shardul Thakur-2022    Shardul Thakur   
2           2022-Gujarat Titans   Lockie Ferguson-2022   Lockie Ferguson   
3     2022-Lucknow Super Giants        Avesh Khan-2022        Avesh Khan   
4         2022-Rajasthan Royals   Prasidh Krishna-2022   Prasidh Krishna   
...                         ...                    ...               ...   
1323                  2013-NONE      Andrew Birch-2013      Andrew Birch   
1324                  2013-NONE    Aaron Phangiso-2013    Aaron Phangiso   
1325                  2013-NONE     Cameron Boyce-2013     Cameron Boyce   
1326                  2013-NONE  Charl Langeveldt-2013  Charl Langeveldt   
1327                  2013-NONE     Sulieman Benn-2013     Sulieman Benn   

     NATIONALITY    TYPE   PRICE SOLD/UNSOLD                  TEAM  YEAR  
0         Indian  Bowler  140.00        SOLD   Chennai Super Kings  2022  
1         Indian  Bowler  107.50        SOLD        Delhi Capitals  2022  
2       Overseas  Bowler  100.00        SOLD        Gujarat Titans  2022  
3         Indian  Bowler  100.00        SOLD  Lucknow Super Giants  2022  
4         Indian  Bowler  100.00        SOLD      Rajasthan Royals  2022  
...          ...     ...     ...         ...                   ...   ...  
1323    Overseas  Bowler    1.17      UNSOLD                  NONE  2013  
1324    Overseas  Bowler    1.17      UNSOLD                  NONE  2013  
1325    Overseas  Bowler    1.17      UNSOLD                  NONE  2013  
1326    Overseas  Bowler    1.17      UNSOLD                  NONE  2013  
1327    Overseas  Bowler    1.17      UNSOLD                  NONE  2013  

[1328 rows x 9 columns]

In [5]:
all_r = a[a['TYPE']=='All-Rounder'].reset_index()
all_r.drop('index',axis=1,inplace=True)

all_r

TID                     PID  \
0                    2022-Punjab Kings   Liam Livingstone-2022   
1     2022-Royal Challengers Bangalore  Wanindu Hasaranga-2022   
2     2022-Royal Challengers Bangalore      Harshal Patel-2022   
3                  2022-Gujarat Titans      Rahul Tewatia-2022   
4                    2022-Punjab Kings      Shahrukh Khan-2022   
...                                ...                     ...   
1400                         2013-NONE     Jandre Coetzee-2013   
1401                         2013-NONE      Alistair Gray-2013   
1402                         2013-NONE   Dwaine Pretorius-2013   
1403                         2013-NONE     Stiaan Van Zyl-2013   
1404                         2013-NONE        David Wiese-2013   

                 PLAYER NATIONALITY         TYPE   PRICE SOLD/UNSOLD  \
0      Liam Livingstone    Overseas  All-Rounder  115.00        SOLD   
1     Wanindu Hasaranga    Overseas  All-Rounder  107.50        SOLD   
2         Harshal Patel      Indian  All-Rounder  107.50        SOLD   
3         Rahul Tewatia      Indian  All-Rounder   90.00        SOLD   
4         Shahrukh Khan      Indian  All-Rounder   90.00        SOLD   
...                 ...         ...          ...     ...         ...   
1400     Jandre Coetzee    Overseas  All-Rounder    1.17      UNSOLD   
1401      Alistair Gray    Overseas  All-Rounder    1.17      UNSOLD   
1402   Dwaine Pretorius    Overseas  All-Rounder    1.17      UNSOLD   
1403     Stiaan Van Zyl    Overseas  All-Rounder    1.17      UNSOLD   
1404        David Wiese    Overseas  All-Rounder    1.17      UNSOLD   

                             TEAM  YEAR  
0                    Punjab Kings  2022  
1     Royal Challengers Bangalore  2022  
2     Royal Challengers Bangalore  2022  
3                  Gujarat Titans  2022  
4                    Punjab Kings  2022  
...                           ...   ...  
1400                         NONE  2013  
1401                         NONE  2013  
1402                         NONE  2013  
1403                         NONE  2013  
1404                         NONE  2013  

[1405 rows x 9 columns]

In [6]:
all_rounder = pd.merge(batting,bowling,on = 'PID')
all_rounder

Name_x  Year_x  Runs_x   4s   6s     SR               PID  \
0     Aaron Finch    2013    4656  552  162   88.5  Aaron Finch-2013   
1     Aaron Finch    2014    7080  738  168   92.7  Aaron Finch-2014   
2     Aaron Finch    2015    3366  348   54   84.8  Aaron Finch-2015   
3     Aaron Finch    2016    5238  540  174   94.6  Aaron Finch-2016   
4     Aaron Finch    2017    3378  348   96  100.3  Aaron Finch-2017   
...           ...     ...     ...  ...  ...    ...               ...   
1115  Zaheer Khan    2008      38    0    0   18.8  Zaheer Khan-2008   
1116  Zaheer Khan    2009      52    0    2   85.7  Zaheer Khan-2009   
1117  Zaheer Khan    2010      54    4    4   80.0  Zaheer Khan-2010   
1118  Zaheer Khan    2011     124   14    0   58.9  Zaheer Khan-2011   
1119  Zaheer Khan    2012      22    4    0   65.9  Zaheer Khan-2012   

           Name_y  Year_y  Overs  Mdns  Runs_y  Wkts  Econ  
0     Aaron Finch    2013   44.4     0     210    12   4.2  
1     Aaron Finch    2014   18.0     0     222     0  13.8  
2     Aaron Finch    2015    1.8     0      18     0   6.0  
3     Aaron Finch    2016   60.0     0     282     0   4.7  
4     Aaron Finch    2017   18.6     0     108     0   5.8  
...           ...     ...    ...   ...     ...   ...   ...  
1115  Zaheer Khan    2008  171.6    28     664    34   3.8  
1116  Zaheer Khan    2009  264.8    12    1622    46   6.5  
1117  Zaheer Khan    2010  182.6    16    1026    26   6.2  
1118  Zaheer Khan    2011  254.2    12    1240    60   4.8  
1119  Zaheer Khan    2012  194.0     4    1096    26   6.1  

[1120 rows x 14 columns]

In [7]:
all_rounder.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1120 entries, 0 to 1119
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name_x  1120 non-null   object 
 1   Year_x  1120 non-null   int64  
 2   Runs_x  1120 non-null   int64  
 3   4s      1120 non-null   int64  
 4   6s      1120 non-null   int64  
 5   SR      1120 non-null   float64
 6   PID     1120 non-null   object 
 7   Name_y  1120 non-null   object 
 8   Year_y  1120 non-null   int64  
 9   Overs   1120 non-null   float64
 10  Mdns    1120 non-null   int64  
 11  Runs_y  1120 non-null   int64  
 12  Wkts    1120 non-null   int64  
 13  Econ    1120 non-null   float64
dtypes: float64(3), int64(8), object(3)
memory usage: 131.2+ KB


In [8]:
all_rounder.drop(['Name_y','Year_y'],axis=1,inplace=True)
all_rounder

Name_x  Year_x  Runs_x   4s   6s     SR               PID  Overs  \
0     Aaron Finch    2013    4656  552  162   88.5  Aaron Finch-2013   44.4   
1     Aaron Finch    2014    7080  738  168   92.7  Aaron Finch-2014   18.0   
2     Aaron Finch    2015    3366  348   54   84.8  Aaron Finch-2015    1.8   
3     Aaron Finch    2016    5238  540  174   94.6  Aaron Finch-2016   60.0   
4     Aaron Finch    2017    3378  348   96  100.3  Aaron Finch-2017   18.6   
...           ...     ...     ...  ...  ...    ...               ...    ...   
1115  Zaheer Khan    2008      38    0    0   18.8  Zaheer Khan-2008  171.6   
1116  Zaheer Khan    2009      52    0    2   85.7  Zaheer Khan-2009  264.8   
1117  Zaheer Khan    2010      54    4    4   80.0  Zaheer Khan-2010  182.6   
1118  Zaheer Khan    2011     124   14    0   58.9  Zaheer Khan-2011  254.2   
1119  Zaheer Khan    2012      22    4    0   65.9  Zaheer Khan-2012  194.0   

      Mdns  Runs_y  Wkts  Econ  
0        0     210    12   4.2  
1        0     222     0  13.8  
2        0      18     0   6.0  
3        0     282     0   4.7  
4        0     108     0   5.8  
...    ...     ...   ...   ...  
1115    28     664    34   3.8  
1116    12    1622    46   6.5  
1117    16    1026    26   6.2  
1118    12    1240    60   4.8  
1119     4    1096    26   6.1  

[1120 rows x 12 columns]

In [9]:
all_rounder = all_rounder.rename(columns={'Name_x':'Name','Year_x':'Year','Runs_x':'Runs_scored','Runs_y':'Runs_given'})
all_rounder

Name  Year  Runs_scored   4s   6s     SR               PID  \
0     Aaron Finch  2013         4656  552  162   88.5  Aaron Finch-2013   
1     Aaron Finch  2014         7080  738  168   92.7  Aaron Finch-2014   
2     Aaron Finch  2015         3366  348   54   84.8  Aaron Finch-2015   
3     Aaron Finch  2016         5238  540  174   94.6  Aaron Finch-2016   
4     Aaron Finch  2017         3378  348   96  100.3  Aaron Finch-2017   
...           ...   ...          ...  ...  ...    ...               ...   
1115  Zaheer Khan  2008           38    0    0   18.8  Zaheer Khan-2008   
1116  Zaheer Khan  2009           52    0    2   85.7  Zaheer Khan-2009   
1117  Zaheer Khan  2010           54    4    4   80.0  Zaheer Khan-2010   
1118  Zaheer Khan  2011          124   14    0   58.9  Zaheer Khan-2011   
1119  Zaheer Khan  2012           22    4    0   65.9  Zaheer Khan-2012   

      Overs  Mdns  Runs_given  Wkts  Econ  
0      44.4     0         210    12   4.2  
1      18.0     0         222     0  13.8  
2       1.8     0          18     0   6.0  
3      60.0     0         282     0   4.7  
4      18.6     0         108     0   5.8  
...     ...   ...         ...   ...   ...  
1115  171.6    28         664    34   3.8  
1116  264.8    12        1622    46   6.5  
1117  182.6    16        1026    26   6.2  
1118  254.2    12        1240    60   4.8  
1119  194.0     4        1096    26   6.1  

[1120 rows x 12 columns]

In [10]:
all_rounder = all_rounder[all_rounder['PID'].isin(all_r['PID'])].reset_index()
all_rounder.drop('index',axis=1,inplace=True)

all_rounder

Name  Year  Runs_scored   4s  6s     SR                  PID  \
0      Albie Morkel  2014          102    0  10  154.3    Albie Morkel-2014   
1     Andre Russell  2014          138   13   6   93.5   Andre Russell-2014   
2        Andrew Tye  2016           20    5   0  100.0      Andrew Tye-2016   
3    Angelo Mathews  2014         2740  234  56   90.8  Angelo Mathews-2014   
4    Angelo Mathews  2015         1006   76  28   89.1  Angelo Mathews-2015   
..              ...   ...          ...  ...  ..    ...                  ...   
168   Wayne Parnell  2015           29    1   0   65.6   Wayne Parnell-2015   
169   Wayne Parnell  2016           41    3   0   65.1   Wayne Parnell-2016   
170   Wayne Parnell  2017          104    7   3  113.7   Wayne Parnell-2017   
171   Wayne Parnell  2021           10    0   0   62.5   Wayne Parnell-2021   
172   Wayne Parnell  2022           70    3   1   50.0   Wayne Parnell-2022   

     Overs  Mdns  Runs_given  Wkts  Econ  
0     24.0     0         236     2   9.8  
1     43.1     0         332    13   8.8  
2     56.0     0         595    10  10.6  
3    327.2    22        1580    48   4.9  
4    178.6    12        1008    32   6.3  
..     ...   ...         ...   ...   ...  
168   40.5     0         288    12   7.6  
169   49.5     2         295    11   5.9  
170   98.1     2         633    21   7.4  
171    1.0     0           5     0   5.0  
172   66.5     2         452    19   6.8  

[173 rows x 12 columns]

In [11]:
batting = batting[batting['PID'].isin(bat['PID'])].reset_index()
batting.drop('index',axis=1,inplace=True)
batting

Name  Year  Runs   4s   6s     SR                   PID
0        Aaron Finch  2013  4656  552  162   88.5      Aaron Finch-2013
1        Aaron Finch  2014  7080  738  168   92.7      Aaron Finch-2014
2        Aaron Finch  2015  3366  348   54   84.8      Aaron Finch-2015
3        Aaron Finch  2016  5238  540  174   94.6      Aaron Finch-2016
4        Aaron Finch  2018  6144  498  264  111.4      Aaron Finch-2018
..               ...   ...   ...  ...  ...    ...                   ...
140      Tim Seifert  2020   704   62   32  120.0      Tim Seifert-2020
141       Tom Banton  2020   283   30    8   94.9       Tom Banton-2020
142      Travis Head  2016  1494  135   30   94.6      Travis Head-2016
143      Travis Head  2018  1362  171    6  100.1      Travis Head-2018
144  Wriddhiman Saha  2014   148   20    0   75.7  Wriddhiman Saha-2014

[145 rows x 7 columns]

In [12]:
bowling = bowling[bowling['PID'].isin(bowl['PID'])].reset_index()
bowling.drop('index',axis=1,inplace=True)

bowling

Name  Year  Overs  Mdns  Runs  Wkts  Econ  \
0          Adam Milne  2014  172.8     6   858    24   5.6   
1          Adam Milne  2015  419.1     9  2082    69   5.1   
2          Adam Milne  2018   19.2     0   159    12   8.2   
3          Adam Milne  2021  108.0     3   939    21   9.0   
4          Adam Milne  2022   96.0     0   654    24   7.4   
..                ...   ...    ...   ...   ...   ...   ...   
170       Umesh Yadav  2018  287.5     0  2175    60   8.0   
171       Umesh Yadav  2022   25.0     0   305    15  12.4   
172       Varun Aaron  2014  138.8     0  1052    20   7.5   
173     Wayne Parnell  2014   93.8     4   577    23   6.9   
174  Yuzvendra Chahal  2022  172.3     0  1105    44   7.0   

                       PID  
0          Adam Milne-2014  
1          Adam Milne-2015  
2          Adam Milne-2018  
3          Adam Milne-2021  
4          Adam Milne-2022  
..                     ...  
170       Umesh Yadav-2018  
171       Umesh Yadav-2022  
172       Varun Aaron-2014  
173     Wayne Parnell-2014  
174  Yuzvendra Chahal-2022  

[175 rows x 8 columns]

In [13]:
bowling = pd.merge(bowling,bowl,on='PID')
bowling

Name  Year  Overs  Mdns  Runs  Wkts  Econ  \
0          Adam Milne  2014  172.8     6   858    24   5.6   
1          Adam Milne  2015  419.1     9  2082    69   5.1   
2          Adam Milne  2018   19.2     0   159    12   8.2   
3          Adam Milne  2021  108.0     3   939    21   9.0   
4          Adam Milne  2022   96.0     0   654    24   7.4   
..                ...   ...    ...   ...   ...   ...   ...   
171       Umesh Yadav  2018  287.5     0  2175    60   8.0   
172       Umesh Yadav  2022   25.0     0   305    15  12.4   
173       Varun Aaron  2014  138.8     0  1052    20   7.5   
174     Wayne Parnell  2014   93.8     4   577    23   6.9   
175  Yuzvendra Chahal  2022  172.3     0  1105    44   7.0   

                       PID                               TID  \
0          Adam Milne-2014                         2014-NONE   
1          Adam Milne-2015  2015-Royal Challengers Bangalore   
2          Adam Milne-2018                         2018-NONE   
3          Adam Milne-2021               2021-Mumbai Indians   
4          Adam Milne-2022          2022-Chennai Super Kings   
..                     ...                               ...   
171       Umesh Yadav-2018  2018-Royal Challengers Bangalore   
172       Umesh Yadav-2022        2022-Kolkata Knight Riders   
173       Varun Aaron-2014  2014-Royal Challengers Bangalore   
174     Wayne Parnell-2014             2014-Delhi Daredevils   
175  Yuzvendra Chahal-2022             2022-Rajasthan Royals   

               PLAYER NATIONALITY    TYPE  PRICE SOLD/UNSOLD  \
0          Adam Milne    Overseas  Bowler    3.0      UNSOLD   
1          Adam Milne    Overseas  Bowler    7.0        SOLD   
2          Adam Milne    Overseas  Bowler    7.5      UNSOLD   
3          Adam Milne    Overseas  Bowler   32.0        SOLD   
4          Adam Milne    Overseas  Bowler   19.0        SOLD   
..                ...         ...     ...    ...         ...   
171       Umesh Yadav    Overseas  Bowler   42.0        SOLD   
172       Umesh Yadav      Indian  Bowler   20.0        SOLD   
173       Varun Aaron    Overseas  Bowler   20.0        SOLD   
174     Wayne Parnell    Overseas  Bowler   10.0        SOLD   
175  Yuzvendra Chahal      Indian  Bowler   65.0        SOLD   

                            TEAM  YEAR  
0                           NONE  2014  
1    Royal Challengers Bangalore  2015  
2                           NONE  2018  
3                 Mumbai Indians  2021  
4            Chennai Super Kings  2022  
..                           ...   ...  
171  Royal Challengers Bangalore  2018  
172        Kolkata Knight Riders  2022  
173  Royal Challengers Bangalore  2014  
174             Delhi Daredevils  2014  
175             Rajasthan Royals  2022  

[176 rows x 16 columns]

In [14]:
bowling.drop(['TID','PLAYER','TEAM','YEAR','TYPE'],axis=1,inplace=True)

In [15]:
bowling

Name  Year  Overs  Mdns  Runs  Wkts  Econ  \
0          Adam Milne  2014  172.8     6   858    24   5.6   
1          Adam Milne  2015  419.1     9  2082    69   5.1   
2          Adam Milne  2018   19.2     0   159    12   8.2   
3          Adam Milne  2021  108.0     3   939    21   9.0   
4          Adam Milne  2022   96.0     0   654    24   7.4   
..                ...   ...    ...   ...   ...   ...   ...   
171       Umesh Yadav  2018  287.5     0  2175    60   8.0   
172       Umesh Yadav  2022   25.0     0   305    15  12.4   
173       Varun Aaron  2014  138.8     0  1052    20   7.5   
174     Wayne Parnell  2014   93.8     4   577    23   6.9   
175  Yuzvendra Chahal  2022  172.3     0  1105    44   7.0   

                       PID NATIONALITY  PRICE SOLD/UNSOLD  
0          Adam Milne-2014    Overseas    3.0      UNSOLD  
1          Adam Milne-2015    Overseas    7.0        SOLD  
2          Adam Milne-2018    Overseas    7.5      UNSOLD  
3          Adam Milne-2021    Overseas   32.0        SOLD  
4          Adam Milne-2022    Overseas   19.0        SOLD  
..                     ...         ...    ...         ...  
171       Umesh Yadav-2018    Overseas   42.0        SOLD  
172       Umesh Yadav-2022      Indian   20.0        SOLD  
173       Varun Aaron-2014    Overseas   20.0        SOLD  
174     Wayne Parnell-2014    Overseas   10.0        SOLD  
175  Yuzvendra Chahal-2022      Indian   65.0        SOLD  

[176 rows x 11 columns]

In [16]:
batting = pd.merge(batting,bat,on='PID')
batting.drop(['TID','PLAYER','TEAM','YEAR','TYPE'],axis=1,inplace=True)
batting

Name  Year  Runs   4s   6s     SR                   PID  \
0        Aaron Finch  2013  4656  552  162   88.5      Aaron Finch-2013   
1        Aaron Finch  2014  7080  738  168   92.7      Aaron Finch-2014   
2        Aaron Finch  2015  3366  348   54   84.8      Aaron Finch-2015   
3        Aaron Finch  2016  5238  540  174   94.6      Aaron Finch-2016   
4        Aaron Finch  2018  6144  498  264  111.4      Aaron Finch-2018   
..               ...   ...   ...  ...  ...    ...                   ...   
140      Tim Seifert  2020   704   62   32  120.0      Tim Seifert-2020   
141       Tom Banton  2020   283   30    8   94.9       Tom Banton-2020   
142      Travis Head  2016  1494  135   30   94.6      Travis Head-2016   
143      Travis Head  2018  1362  171    6  100.1      Travis Head-2018   
144  Wriddhiman Saha  2014   148   20    0   75.7  Wriddhiman Saha-2014   

    NATIONALITY  PRICE SOLD/UNSOLD  
0      Overseas   11.7      UNSOLD  
1      Overseas   40.0        SOLD  
2      Overseas   32.0        SOLD  
3      Overseas   10.0        SOLD  
4      Overseas   62.0        SOLD  
..          ...    ...         ...  
140    Overseas    5.0      UNSOLD  
141    Overseas   10.0        SOLD  
142    Overseas    5.0        SOLD  
143    Overseas   15.0      UNSOLD  
144      Indian   22.0        SOLD  

[145 rows x 10 columns]

In [17]:
all_rounder = pd.merge(all_rounder,all_r,on='PID')
all_rounder.drop(['TID','PLAYER','TEAM','YEAR','TYPE'],axis=1,inplace=True)
all_rounder

Name  Year  Runs_scored   4s  6s     SR                  PID  \
0      Albie Morkel  2014          102    0  10  154.3    Albie Morkel-2014   
1     Andre Russell  2014          138   13   6   93.5   Andre Russell-2014   
2        Andrew Tye  2016           20    5   0  100.0      Andrew Tye-2016   
3    Angelo Mathews  2014         2740  234  56   90.8  Angelo Mathews-2014   
4    Angelo Mathews  2015         1006   76  28   89.1  Angelo Mathews-2015   
..              ...   ...          ...  ...  ..    ...                  ...   
169   Wayne Parnell  2015           29    1   0   65.6   Wayne Parnell-2015   
170   Wayne Parnell  2016           41    3   0   65.1   Wayne Parnell-2016   
171   Wayne Parnell  2017          104    7   3  113.7   Wayne Parnell-2017   
172   Wayne Parnell  2021           10    0   0   62.5   Wayne Parnell-2021   
173   Wayne Parnell  2022           70    3   1   50.0   Wayne Parnell-2022   

     Overs  Mdns  Runs_given  Wkts  Econ NATIONALITY  PRICE SOLD/UNSOLD  
0     24.0     0         236     2   9.8    Overseas   24.0        SOLD  
1     43.1     0         332    13   8.8    Overseas    6.0        SOLD  
2     56.0     0         595    10  10.6    Overseas    5.0        SOLD  
3    327.2    22        1580    48   4.9    Overseas   20.0      UNSOLD  
4    178.6    12        1008    32   6.3    Overseas   75.0        SOLD  
..     ...   ...         ...   ...   ...         ...    ...         ...  
169   40.5     0         288    12   7.6    Overseas    3.0      UNSOLD  
170   49.5     2         295    11   5.9    Overseas    5.0      UNSOLD  
171   98.1     2         633    21   7.4    Overseas    5.0      UNSOLD  
172    1.0     0           5     0   5.0    Overseas    5.0      UNSOLD  
173   66.5     2         452    19   6.8    Overseas    5.0      UNSOLD  

[174 rows x 15 columns]

In [44]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, RandomForestClassifier, GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics

## Pre-processing for Model

In [21]:
bat_us = batting.drop(['Name','PID','PRICE'],axis=1)
bat_us

Year  Runs   4s   6s     SR NATIONALITY SOLD/UNSOLD
0    2013  4656  552  162   88.5    Overseas      UNSOLD
1    2014  7080  738  168   92.7    Overseas        SOLD
2    2015  3366  348   54   84.8    Overseas        SOLD
3    2016  5238  540  174   94.6    Overseas        SOLD
4    2018  6144  498  264  111.4    Overseas        SOLD
..    ...   ...  ...  ...    ...         ...         ...
140  2020   704   62   32  120.0    Overseas      UNSOLD
141  2020   283   30    8   94.9    Overseas        SOLD
142  2016  1494  135   30   94.6    Overseas        SOLD
143  2018  1362  171    6  100.1    Overseas      UNSOLD
144  2014   148   20    0   75.7      Indian        SOLD

[145 rows x 7 columns]

In [22]:
bat_us['NATIONALITY'] = np.where(bat_us['NATIONALITY']=='Overseas',1,0)
bat_us['SOLD/UNSOLD'] = np.where(bat_us['SOLD/UNSOLD']=='SOLD',1,0)
bat_us

Year  Runs   4s   6s     SR  NATIONALITY  SOLD/UNSOLD
0    2013  4656  552  162   88.5            1            0
1    2014  7080  738  168   92.7            1            1
2    2015  3366  348   54   84.8            1            1
3    2016  5238  540  174   94.6            1            1
4    2018  6144  498  264  111.4            1            1
..    ...   ...  ...  ...    ...          ...          ...
140  2020   704   62   32  120.0            1            0
141  2020   283   30    8   94.9            1            1
142  2016  1494  135   30   94.6            1            1
143  2018  1362  171    6  100.1            1            0
144  2014   148   20    0   75.7            0            1

[145 rows x 7 columns]

In [23]:
bat_us.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 145 entries, 0 to 144
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Year         145 non-null    int64  
 1   Runs         145 non-null    int64  
 2   4s           145 non-null    int64  
 3   6s           145 non-null    int64  
 4   SR           145 non-null    float64
 5   NATIONALITY  145 non-null    int32  
 6   SOLD/UNSOLD  145 non-null    int32  
dtypes: float64(1), int32(2), int64(4)
memory usage: 7.9 KB


In [28]:
X_bat_us = bat_us.drop(['SOLD/UNSOLD'],axis=1)
y_bat_us = bat_us['SOLD/UNSOLD']

In [30]:
X_train_bat_us, X_test_bat_us, y_train_bat_us, y_test_bat_us = train_test_split(X_bat_us,y_bat_us,test_size=0.3,random_state=1)

In [31]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
X_train_bat_us = minmax.fit_transform(X_train_bat_us)
X_test_bat_us = minmax.transform(X_test_bat_us)

### Logistic

In [32]:
model = LogisticRegression()
model.fit(X_train_bat_us,y_train_bat_us)

LogisticRegression()

In [33]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

0.6831683168316832
[[34 12]
 [20 35]]
              precision    recall  f1-score   support

           0       0.63      0.74      0.68        46
           1       0.74      0.64      0.69        55

    accuracy                           0.68       101
   macro avg       0.69      0.69      0.68       101
weighted avg       0.69      0.68      0.68       101



In [34]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.6136363636363636
[[15  4]
 [13 12]]
              precision    recall  f1-score   support

           0       0.54      0.79      0.64        19
           1       0.75      0.48      0.59        25

    accuracy                           0.61        44
   macro avg       0.64      0.63      0.61        44
weighted avg       0.66      0.61      0.61        44



### LDA

In [35]:
model = LinearDiscriminantAnalysis()
model.fit(X_train_bat_us,y_train_bat_us)

LinearDiscriminantAnalysis()

In [36]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

0.7326732673267327
[[36 10]
 [17 38]]
              precision    recall  f1-score   support

           0       0.68      0.78      0.73        46
           1       0.79      0.69      0.74        55

    accuracy                           0.73       101
   macro avg       0.74      0.74      0.73       101
weighted avg       0.74      0.73      0.73       101



In [37]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.5909090909090909
[[14  5]
 [13 12]]
              precision    recall  f1-score   support

           0       0.52      0.74      0.61        19
           1       0.71      0.48      0.57        25

    accuracy                           0.59        44
   macro avg       0.61      0.61      0.59        44
weighted avg       0.62      0.59      0.59        44



### KNN

In [38]:
model = KNeighborsClassifier()
model.fit(X_train_bat_us,y_train_bat_us)

KNeighborsClassifier()

In [39]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

0.7821782178217822
[[36 10]
 [12 43]]
              precision    recall  f1-score   support

           0       0.75      0.78      0.77        46
           1       0.81      0.78      0.80        55

    accuracy                           0.78       101
   macro avg       0.78      0.78      0.78       101
weighted avg       0.78      0.78      0.78       101



C:\Users\72raj\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\72raj\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

In [40]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.6136363636363636
[[15  4]
 [13 12]]
              precision    recall  f1-score   support

           0       0.54      0.79      0.64        19
           1       0.75      0.48      0.59        25

    accuracy                           0.61        44
   macro avg       0.64      0.63      0.61        44
weighted avg       0.66      0.61      0.61        44



C:\Users\72raj\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\72raj\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

### Naive Bayes

In [41]:
model = GaussianNB()
model.fit(X_train_bat_us,y_train_bat_us)

GaussianNB()

In [42]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

0.6138613861386139
[[45  1]
 [38 17]]
              precision    recall  f1-score   support

           0       0.54      0.98      0.70        46
           1       0.94      0.31      0.47        55

    accuracy                           0.61       101
   macro avg       0.74      0.64      0.58       101
weighted avg       0.76      0.61      0.57       101



In [43]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.5909090909090909
[[19  0]
 [18  7]]
              precision    recall  f1-score   support

           0       0.51      1.00      0.68        19
           1       1.00      0.28      0.44        25

    accuracy                           0.59        44
   macro avg       0.76      0.64      0.56        44
weighted avg       0.79      0.59      0.54        44



### RandomForestClassifier

In [45]:
model = RandomForestClassifier()
model.fit(X_train_bat_us,y_train_bat_us)

RandomForestClassifier()

In [46]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

1.0
[[46  0]
 [ 0 55]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        46
           1       1.00      1.00      1.00        55

    accuracy                           1.00       101
   macro avg       1.00      1.00      1.00       101
weighted avg       1.00      1.00      1.00       101



In [47]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.7045454545454546
[[16  3]
 [10 15]]
              precision    recall  f1-score   support

           0       0.62      0.84      0.71        19
           1       0.83      0.60      0.70        25

    accuracy                           0.70        44
   macro avg       0.72      0.72      0.70        44
weighted avg       0.74      0.70      0.70        44



### XGBoostClassifier

In [50]:
import xgboost as xgb
model=xgb.XGBClassifier(max_depth=1,random_state=1,eval_metric='error',scale_pos_weight=6)
model.fit(X_train_bat_us, y_train_bat_us)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='error', feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=1, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=1, ...)

In [51]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

0.7029702970297029
[[16 30]
 [ 0 55]]
              precision    recall  f1-score   support

           0       1.00      0.35      0.52        46
           1       0.65      1.00      0.79        55

    accuracy                           0.70       101
   macro avg       0.82      0.67      0.65       101
weighted avg       0.81      0.70      0.66       101



In [52]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.6590909090909091
[[ 5 14]
 [ 1 24]]
              precision    recall  f1-score   support

           0       0.83      0.26      0.40        19
           1       0.63      0.96      0.76        25

    accuracy                           0.66        44
   macro avg       0.73      0.61      0.58        44
weighted avg       0.72      0.66      0.61        44



### GradientClassifier

In [53]:
model = GradientBoostingClassifier()
model.fit(X_train_bat_us, y_train_bat_us)

GradientBoostingClassifier()

In [54]:
y_train_predict = model.predict(X_train_bat_us)
model_score = model.score(X_train_bat_us,y_train_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_train_bat_us,y_train_predict))
print(metrics.classification_report(y_train_bat_us,y_train_predict))

1.0
[[46  0]
 [ 0 55]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        46
           1       1.00      1.00      1.00        55

    accuracy                           1.00       101
   macro avg       1.00      1.00      1.00       101
weighted avg       1.00      1.00      1.00       101



In [55]:
y_test_predict = model.predict(X_test_bat_us)
model_score = model.score(X_test_bat_us,y_test_bat_us)
print(model_score)
print(metrics.confusion_matrix(y_test_bat_us,y_test_predict))
print(metrics.classification_report(y_test_bat_us,y_test_predict))

0.7045454545454546
[[18  1]
 [12 13]]
              precision    recall  f1-score   support

           0       0.60      0.95      0.73        19
           1       0.93      0.52      0.67        25

    accuracy                           0.70        44
   macro avg       0.76      0.73      0.70        44
weighted avg       0.79      0.70      0.70        44



Selecting XGBoost as it has got highest Recall value in both Train and Test.